// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Productcatalog.Data;

#nullable disable

namespace Productcatalog.Migrations
{
    [DbContext(typeof(ProductenDBContext))]
    partial class ProductenDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Productcatalog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Body Care"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Decoration"
                        });
                });

            modelBuilder.Entity("Productcatalog.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Aloe Body Cream",
                            Price = 7.50m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Name = "Aloe Toothpaste",
                            Price = 2.60m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Name = "Seaweed Jam",
                            Price = 5.50m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Name = "Chia seed brownie",
                            Price = 1.80m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            Name = "Cactus euphorbia",
                            Price = 6.80m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Name = "Essential oil diffuser ",
                            Price = 1.80m
                        });
                });

            modelBuilder.Entity("Productcatalog.Models.ViewModels.ProductenViewModel", b =>
                {
                    b.Property<int>("GeselecteerdeCategoryId")
                        .HasColumnType("int");

                    b.ToTable("ProductenViewModels");
                });

            modelBuilder.Entity("Productcatalog.Models.Product", b =>
                {
                    b.HasOne("Productcatalog.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Productcatalog.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
